### ISSUE TITLE
Added UXG Max Gateway, USG Dashboard shows extra Panels

### ISSUE THREAD

**Issue by lslamp** [unpoller/dashboards#34] opened 2024-04-20 07:44 UTC
I have just updated my UXG Lite to the UGX Max Gateway device.
The switch went well, only when I open the UniFi-Poller: USG Insights - InfluxDB Dashboard, I am presented with the following dashoard.
![image](https://github.com/unpoller/dashboards/assets/6013759/feb36e3f-a90e-4a88-ba30-ec3c72c187b5)

I think that this was caused by me renaming the gateway after the installation.
The current name is ICANGateway. No matter what I try I cannot seem to remove the other two Gateway names.
I did try to delete these but then it also ended up deleting the ICANGateway as well.
Looking at the separate dashboards, two of the 3 have no data. The ICANGateway has data as expected.
How can I delete the second two dashboards. Below are all 3 dashboards.
![image](https://github.com/unpoller/dashboards/assets/6013759/eade4206-3c33-45fa-9967-9fee5e7b55da)

![image](https://github.com/unpoller/dashboards/assets/6013759/8ae159bb-2725-4253-af92-b59d4563d877)

![image](https://github.com/unpoller/dashboards/assets/6013759/c2df69cf-8c11-4f83-bc3f-5e61aa0c853b)

Thanks
Lawrence

**Comment by platinummonkey** [comment] 2024-05-08 15:58
closing for dupe of #35

**Closed by platinummonkey** 2024-05-08 15:58 UTC
