### ISSUE TITLE
Last version of Unifi Controller seems to remove SITE from tables

### ISSUE THREAD

**Issue by SVLoneStar** [unpoller/dashboards#25] opened 2023-12-22 09:27 UTC
I manually had to remove the 'WHERE "site"=/^$site$/' from all graphs in the v2 Dashboards to again see values.

**Comment by amoksworld** [comment] 2023-12-27 13:43
It seems they changed the database layout, too...

**Comment by vidia** [comment] 2024-02-01 02:34
From what I can tell, the Site is still set, but it includes (for me at least) a new `(default)` suffix that's causing all the regex matching to break. 

I'm not sure how it ended up being added or when or if that's the cause vs. a change in Grafana parsing, but switching references of `$Site` to `${Site:regex}` seems to solve it.

**Comment by platinummonkey** [comment] 2024-02-21 10:50
This was fixed with #25

**Closed by platinummonkey** 2024-02-21 10:50 UTC
Labels: bug, good first issue, help wanted
